### ISSUE TITLE
Gradle task compileAutomationTestJava failed

### ISSUE THREAD

**Issue by BLeQuerrec** [signalapp/Signal-Android#3761]
`$ ./gradlew connectedCheck --info` fails:

```
[...]
Executing task ':compileAutomationTestJava' (up-to-date check took 0.513 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':compileAutomationTestJava'.
Compiling with JDK Java compiler API.
/home/bastien/Android/TextSecure/test/androidTest/java/org/thoughtcrime/securesms/jobs/CleanPreKeysJobTest.java:145: error: <anonymous org.thoughtcrime.securesms.jobs.CleanPreKeysJobTest$TestModule$1> is not abstract and does not override abstract method create() in SignedPreKeyStoreFactory
      return new AxolotlStorageModule.SignedPreKeyStoreFactory() {
                                                                 ^
/home/bastien/Android/TextSecure/test/androidTest/java/org/thoughtcrime/securesms/jobs/CleanPreKeysJobTest.java:146: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/bastien/Android/TextSecure/test/androidTest/java/org/thoughtcrime/securesms/jobs/DeliveryReceiptJobTest.java:91: error: <anonymous org.thoughtcrime.securesms.jobs.DeliveryReceiptJobTest$TestModule$1> is not abstract and does not override abstract method create() in TextSecureMessageSenderFactory
      return new TextSecureMessageSenderFactory() {
                                                  ^
/home/bastien/Android/TextSecure/test/androidTest/java/org/thoughtcrime/securesms/jobs/DeliveryReceiptJobTest.java:92: error: method does not override or implement a method from a supertype
        @Override
        ^
4 errors
:compileAutomationTestJava FAILED
:compileAutomationTestJava (Thread[main,5,main]) completed. Took 2.659 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileAutomationTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 7 mins 56.541 secs
Stopped 0 compiler daemon(s).
```

Environment info:

```
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)
$ cat /etc/os-release
NAME=Fedora
VERSION="22 (Twenty Two)"
ID=fedora
VERSION_ID=22
PRETTY_NAME="Fedora 22 (Twenty Two)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:22"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=22
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=22
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

I think the bug was introduced in 8d9ae731ef4124dbb3900e0b62cc98199b64c783.

**Comment by automated-signal** [comment]
GitHub Issue Cleanup:
See #7598 for more information.
