### ISSUE TITLE
Crashes after update to 7.21.0 when initiating outbound calls

### ISSUE THREAD

**Issue by ostasevych** [signalapp/Signal-Android#13737]
### Guidelines

- [X] I have searched searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] This isn't a feature request or a discussion topic

### Bug description

I've got the last update via Google Playmarket to v7.21.0. Everytime I try to make outbound call the app crashes. Rebooting, cleaning the cache doesn't help.

### Device

Pixel 5A

### Android version

14

### Signal version

7.21.0

**Comment by ostasevych** [comment]
Additionally, cannot import chat history to older versions... :(

**Comment by Senelba** [comment]
Yes I can confirm, app crashes when receiving/making calls, unable to backup to an older version

**Comment by jaedog** [comment]
I noticed this crash issue on GrapheneOS Android 15 Alpha and thought it was the updated android causing the issues! Here is the crash log I got:
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024101700:user/release-keys
flags: dev options enabled
package: org.thoughtcrime.securesms:147100
process: org.thoughtcrime.securesms
processUptime: 4955 + 371 ms
installer: com.android.vending

java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~HRhhFYrSk6KqgJ8Eq83m7w==/org.thoughtcrime.securesms-Oxd2BTdV2j_OVID01_y8Gw==/base.apk!classes6.dex)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~HRhhFYrSk6KqgJ8Eq83m7w==/org.thoughtcrime.securesms-Oxd2BTdV2j_OVID01_y8Gw==/base.apk!classes6.dex).(:0)
```

**Comment by greyson-signal** [comment]
Thank you for the report! We have a fix pending, but unfortunately some Play Store delays are preventing us from getting it out as quickly as we'd like. Apologies!

**Comment by ostasevych** [comment]
> Thank you for the report! We have a fix pending, but unfortunately some Play Store delays are preventing us from getting it out as quickly as we'd like. Apologies!

Can you share the fix, eg via google drive or by publishing on f-droid?

**Comment by ayushnix** [comment]
I've hit bugs in the beta version in the past few weeks where I've been unable to call or message my family and friends and I guess that's okay but not being able to create backups or import them (as @ostasevych mentioned) doesn't sound okay to me.

Will I be able to import a backup I made from 7.21.0 beta version into the latest stable version?

**Comment by Senelba** [comment]
> I've hit bugs in the beta version in the past few weeks where I've been unable to call or message my family and friends and I guess that's okay but not being able to create backups or import them (as @ostasevych mentioned) doesn't sound okay to me.
> 
> Will I be able to import a backup I made from 7.21.0 beta version into the latest stable version?

No it didn't work for me

**Comment by ayushnix** [comment]
So now I'm not sure if these backups I've made from 7.21.0 are worthless or if the stable version needs an update to be able to import those backups.

**Comment by Senelba** [comment]
Yes I guess so, I don't have another phone handy to try transfering from another phone method, but as far as I know an older version won't be able to restore from a backup made on a newer version.

**Comment by farewelltospring** [comment]
I built an apk locally using the latest source on Github, but I still encounter this error.

**Comment by farewelltospring** [comment]
logcat
```
--------- beginning of crash
10-17 19:57:26.649   820  1746 E AndroidRuntime: FATAL EXCEPTION: pool-24-thread-1
10-17 19:57:26.649   820  1746 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 820
10-17 19:57:26.649   820  1746 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in base.apk!classes2.dex)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1074)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-17 19:57:26.649   820  1746 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
10-17 19:57:26.649   820  1746 I ActiveCallManager: Uncaught exception - releasing proximity lock
10-17 19:57:26.649   820  1746 I ActiveCallManager: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in base.apk!classes2.dex)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1074)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-17 19:57:26.649   820  1746 I ActiveCallManager:     at java.lang.Thread.run(Thread.java:1012)
10-17 19:57:26.650   820  1746 D ProximityLock: Released proximity lock:false
10-17 19:57:26.650   820  1746 D LockManager: Entered Lock State: SLEEP
10-17 19:57:26.650   820  1746 D AccelerometerListener: enable(false)
10-17 19:57:26.653   820  1746 E SignalUncaughtException: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in base.apk!classes2.dex)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1074)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-17 19:57:26.653   820  1746 E SignalUncaughtException:       at java.lang.Thread.run(Thread.java:1012)
10-17 19:57:26.723   820  1732 D SignalAudioManager31: Switching to new device of type 1 from 1
10-17 19:57:26.724   820  1732 W SignalAudioManager31: Succeeded in setting 2 (type: 1) as communication device.
10-17 19:57:26.724   820  1690 V SignalCallManager: Processing action: onAudioDeviceChanged, handler: OutgoingCallActionProce
10-17 19:57:26.724   820  1690 I OutgoingCallActionProce: handleAudioDeviceChanged(): active: EARPIECE available: [EARPIECE, SPEAKER_PHONE]
10-17 19:57:26.724   820  1690 I OutgoingCallActionProce: handleAudioDeviceChanged(): call not connected, not updating phone state
10-17 19:57:26.724   820   820 I JobManager: onConstraintMet(NotInCallConstraintObse)
10-17 19:57:26.724   820   820 I WebRtcCallActivity: Got message from service: <no change>
10-17 19:57:26.726   820   820 D WebRtcAudioOutputToggle: Switching button drawable to HANDSET
10-17 19:57:26.805   820  1746 I JobManager: Successfully flushed.
10-17 19:57:26.815   820  1746 I Process : Sending signal. PID: 820 SIG: 9
```

**Comment by ayushnix** [comment]
Can one of the Signal devs confirm if importing backups made from a beta version into a stable versions is possible? I have a backup of almost 10GB and I'd hate to loose all the chats with my family.

**Comment by farewelltospring** [comment]
@ayushnix I don't work at Signal (yet :pleading_face: :point_right: :point_left: ) but it seems like https://github.com/signalapp/Signal-Android/blob/main/app/src/main/java/org/thoughtcrime/securesms/backup/FullBackupImporter.java#L158 is what prevents you from importing backups from a new Signal backup into an old Signal app. Maybe try building an apk without that condition and see what happens? Or hope that the bug fix gets released soon...

**Comment by githubuser6000** [comment]
Can confirm. Happens with incoming calls too. App dies on incoming call and am unable to pickup. 

```
10-17 19:46:55.840 25579 25302 E AndroidRuntime: FATAL EXCEPTION: pool-47-thread-1
10-17 19:46:55.840 25579 25302 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 25579
10-17 19:46:55.840 25579 25302 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-17 19:46:55.840 25579 25302 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: FATAL EXCEPTION: pool-23-thread-1
10-17 20:04:19.332 25768 25879 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 25768
10-17 20:04:19.332 25768 25879 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-17 20:04:19.332 25768 25879 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: FATAL EXCEPTION: pool-22-thread-1
10-17 21:38:55.673  3040  3220 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 3040
10-17 21:38:55.673  3040  3220 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-17 21:38:55.673  3040  3220 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: FATAL EXCEPTION: pool-26-thread-1
10-17 23:35:24.945 11246 11349 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 11246
10-17 23:35:24.945 11246 11349 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-17 23:35:24.945 11246 11349 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: FATAL EXCEPTION: pool-16-thread-1
10-17 23:42:41.021 11415 11858 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 11415
10-17 23:42:41.021 11415 11858 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-17 23:42:41.021 11415 11858 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: FATAL EXCEPTION: pool-28-thread-1
10-18 02:24:29.476 12226 18307 E AndroidRuntime: Process: org.thoughtcrime.securesms, PID: 12226
10-18 02:24:29.476 12226 18307 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~5fRfvx1FL8yXLkk5lltQGw==/org.thoughtcrime.securesms-ks_8i9NRSuvYC6gjoYjSxw==/base.apk!classes6.dex)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1063)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-18 02:24:29.476 12226 18307 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Nashaathu** [comment]
Do we have any source for beta updates other than playstore?

**Comment by jaedog** [comment]
Latest beta 7.21.1 still crashes.

Log:
```
type: crash
osVersion: google/komodo/komodo:15/AP3A.241005.015/2024101701:user/release-keys
flags: dev options enabled
package: org.thoughtcrime.securesms:147200
process: org.thoughtcrime.securesms
processUptime: 8591 + 255 ms
installer: com.android.vending

java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~ug9w6fVcK2szwaRf8rAj3Q==/org.thoughtcrime.securesms-y2yxhir918zwj5ml9v7yIw==/base.apk!classes6.dex)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.mapToIceServers(SignalCallManager.java:1074)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.lambda$retrieveTurnServers$86(SignalCallManager.java:1032)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager.$r8$lambda$frT7W1qaWhaEe-GBKUJj0jsDRv0(SignalCallManager.java:0)
	at org.thoughtcrime.securesms.service.webrtc.SignalCallManager$$ExternalSyntheticLambda85.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at [[ ↑↑ Original Trace ↑↑ ]].(:0)
	at [[ ↓↓ Exception Message ↓↓ ]].(:0)
	at No interface method toList()Ljava/util/List; in class Lj$/util/stream/Stream; or its super classes (declaration of 'j$.util.stream.Stream' appears in /data/app/~~ug9w6fVcK2szwaRf8rAj3Q==/org.thoughtcrime.securesms-y2yxhir918zwj5ml9v7yIw==/base.apk!classes6.dex).(:0)
```

**Comment by Senelba** [comment]
The problem still persists with the new published version 7.21.1

**Comment by ostasevych** [comment]
> The problem still persists with the new published version 7.21.1

I confirm the same.

**Comment by Nashaathu** [comment]
As before i can call and receive group calls , and the problem persists in one to one calls.

**Comment by Doormouse2House** [comment]
Does anyone *not* have this issue?

**Comment by EurekaUA** [comment]
The problem persists with the newly published version 7.21.1

**Comment by Doormouse2House** [comment]
> Does anyone _not_ have this issue?

Am trying to understand if this is device specific, or a generic bug... Not knowing too much about the libraries, dependencies etc in the codebase.

**Comment by XanderXAJ** [comment]
I'm also getting the issue with the latest published version 7.21.1. Here's my debug log:
https://debuglogs.org/android/7.21.1/582778d3108b720fdd5ac2fd8e6fa150f020649519efb02ef73375498ba7331d

**Comment by greyson-signal** [comment]
Unfortunately the bug wasn't fully fixed in 7.21.1. There's a 7.21.2 that should fix the remaining issues that will be out as soon as the Play Store approves it. Again, sorry for the very bad bug!

**Comment by Doormouse2House** [comment]
> Unfortunately the bug wasn't fully fixed in 7.21.1. There's a 7.21.2 that should fix the remaining issues that will be out as soon as the Play Store approves it. Again, sorry for the very bad bug!

Thanks for confirming

**Comment by ostasevych** [comment]
Hi!

Can you publish the fix on f-droid?

Thanks!

Best regards
Oleksa

пт, 18 жовт. 2024 р., 21:35 користувач Greyson Parrelli <
***@***.***> пише:

**Comment by LucaBrolli** [comment]
I got the crash while calling/receiving calls issue after the very last update this morning. Before of that I got no issue.

Galaxy S24+

**Comment by farewelltospring** [comment]
I built version 7.21.2 locally and it's fixed now.

**Comment by ostasevych** [comment]
> I built version 7.21.2 locally and it's fixed now.

Can you share it somehow?

**Comment by farewelltospring** [comment]
> > I built version 7.21.2 locally and it's fixed now.
> 
> Can you share it somehow?

Unfortunately no. My local builds are signed with my personal keys and not Signal's so Android won't let you install the apk I have unless you delete Signal first. And then you would have to use my apk for all future updates. A small price that I am willing to pay but I don't think you want to go through the hassle of asking me to email my apk to you every time you want to update Signal :wink:

Just wait for the official update

**Comment by ostasevych** [comment]
> > > I built version 7.21.2 locally and it's fixed now.
> > 
> > 
> > Can you share it somehow?
> 
> Unfortunately no. My local builds are signed with my personal keys and not Signal's so Android won't let you install the apk I have unless you delete Signal first. And then you would have to use my apk for all future updates. A small price that I am willing to pay but I don't think you want to go through the hassle of asking me to email my apk to you every time you want to update Signal 😉
> 
> Just wait for the official update

I see. Thanks a lot for a good explanation.

**Comment by greyson-signal** [comment]
Official update is live in the store, closing. Sorry for all of the trouble!

**Comment by avi-singh** [comment]
The latest version is now crashing, not sure if it's related with these changes, but the moment I open the app, it crashes.

**Comment by ostasevych** [comment]
it works with the last fix! Many thanks!

**Comment by jaedog** [comment]
Thanks! Fixed for me as well.

**Comment by Doormouse2House** [comment]
Thanks for the quick turnaround
